apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bloggingapp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: blogging.charifcourses.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bloggingapp-ssvc
            port:
              number: 80
